"""Centralized rejection reason constants for pipeline auditability."""

from __future__ import annotations

CHOPPY_MARKET_NO_TRADE = "CHOPPY_MARKET_NO_TRADE"
LOW_VOLATILITY_NO_TRADE = "LOW_VOLATILITY_NO_TRADE"
REGIME_NOT_TRADEABLE = "REGIME_NOT_TRADEABLE"
STRATEGY_SELECTION_CONTEXT_MISSING = "STRATEGY_SELECTION_CONTEXT_MISSING"
NO_ACTIVE_STRATEGIES = "NO_ACTIVE_STRATEGIES"
UNSUPPORTED_REGIME_FOR_STRATEGY = "UNSUPPORTED_REGIME_FOR_STRATEGY"
NO_STRATEGY_MATCHED_REGIME = "NO_STRATEGY_MATCHED_REGIME"
NO_STRATEGY_PASSED_CONFIG = "NO_STRATEGY_PASSED_CONFIG"
MTF_POLICY_BLOCKED = "MTF_POLICY_BLOCKED"
MTF_POLICY_NO_SETUP = "MTF_POLICY_NO_SETUP"
BAD_MARKET_STRUCTURE_LOCATION = "BAD_MARKET_STRUCTURE_LOCATION"
BUY_TOO_CLOSE_TO_RESISTANCE = "BUY_TOO_CLOSE_TO_RESISTANCE"
SELL_TOO_CLOSE_TO_SUPPORT = "SELL_TOO_CLOSE_TO_SUPPORT"
PRICE_IN_NO_TRADE_ZONE = "PRICE_IN_NO_TRADE_ZONE"
MARKET_STRUCTURE_CONFLICT = "MARKET_STRUCTURE_CONFLICT"
INSUFFICIENT_ROOM_TO_TARGET_ZONE = "INSUFFICIENT_ROOM_TO_TARGET_ZONE"
MARKET_STRUCTURE_MISSING = "MARKET_STRUCTURE_MISSING"
MARKET_STRUCTURE_UNRELIABLE = "MARKET_STRUCTURE_UNRELIABLE"

# Keep generic fallback reason available for backward compatibility.
NO_STRATEGY_SELECTED = "NO_STRATEGY_SELECTED"
