"""Centralized rejection reason constants for pipeline auditability."""

from __future__ import annotations

CHOPPY_MARKET_NO_TRADE = "CHOPPY_MARKET_NO_TRADE"
LOW_VOLATILITY_NO_TRADE = "LOW_VOLATILITY_NO_TRADE"
REGIME_NOT_TRADEABLE = "REGIME_NOT_TRADEABLE"
STRATEGY_SELECTION_CONTEXT_MISSING = "STRATEGY_SELECTION_CONTEXT_MISSING"
NO_ACTIVE_STRATEGIES = "NO_ACTIVE_STRATEGIES"
UNSUPPORTED_REGIME_FOR_STRATEGY = "UNSUPPORTED_REGIME_FOR_STRATEGY"
NO_STRATEGY_MATCHED_REGIME = "NO_STRATEGY_MATCHED_REGIME"
NO_STRATEGY_PASSED_CONFIG = "NO_STRATEGY_PASSED_CONFIG"
MTF_POLICY_BLOCKED = "MTF_POLICY_BLOCKED"
MTF_POLICY_NO_SETUP = "MTF_POLICY_NO_SETUP"

# Keep generic fallback reason available for backward compatibility.
NO_STRATEGY_SELECTED = "NO_STRATEGY_SELECTED"
