"""add_domain_models_foundation

Revision ID: 745830deb06e
Revises: 20260527_0001
Create Date: 2026-05-27 14:47:27.104333
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '745830deb06e'
down_revision = '20260527_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kill_switch_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('activated_by', sa.String(length=100), nullable=True),
    sa.Column('deactivated_by', sa.String(length=100), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_kill_switch_states_is_active_created_at', 'kill_switch_states', ['is_active', 'created_at'], unique=False, schema='trading')
    op.create_table('safety_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('related_trace_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_safety_events_event_type_created_at', 'safety_events', ['event_type', 'created_at'], unique=False, schema='trading')
    op.create_index('ix_safety_events_severity', 'safety_events', ['severity'], unique=False, schema='trading')
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='trading'
    )
    op.create_index('ix_strategies_code', 'strategies', ['code'], unique=False, schema='trading')
    op.create_table('symbols',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('asset_class', sa.String(length=32), nullable=False),
    sa.Column('digits', sa.Integer(), nullable=False),
    sa.Column('point', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='trading'
    )
    op.create_index('ix_symbols_name', 'symbols', ['name'], unique=False, schema='trading')
    op.create_table('timeframes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='trading'
    )
    op.create_index('ix_timeframes_code', 'timeframes', ['code'], unique=False, schema='trading')
    op.create_table('trading_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('broker_server', sa.String(length=255), nullable=False),
    sa.Column('base_currency', sa.String(length=16), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number'),
    schema='trading'
    )
    op.create_index('ix_trading_accounts_account_number', 'trading_accounts', ['account_number'], unique=False, schema='trading')
    op.create_index('ix_trading_accounts_broker_server', 'trading_accounts', ['broker_server'], unique=False, schema='trading')
    op.create_table('account_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('equity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('margin', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('free_margin', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('margin_level', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('profit', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading.trading_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_account_snapshots_account_id_snapshot_time', 'account_snapshots', ['account_id', 'snapshot_time'], unique=False, schema='trading')
    op.create_table('broker_health_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('is_trade_allowed', sa.Boolean(), nullable=False),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('spread', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['trading.symbols.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_broker_health_checks_checked_at', 'broker_health_checks', ['checked_at'], unique=False, schema='trading')
    op.create_index('ix_broker_health_checks_is_healthy', 'broker_health_checks', ['is_healthy'], unique=False, schema='trading')
    op.create_table('candles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('timeframe_id', sa.UUID(), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('tick_volume', sa.BigInteger(), nullable=False),
    sa.Column('spread', sa.Integer(), nullable=True),
    sa.Column('real_volume', sa.BigInteger(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['trading.symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['trading.timeframes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_candles_symbol_tf_open_time', 'candles', ['symbol_id', 'timeframe_id', 'open_time'], unique=False, schema='trading')
    op.create_table('data_quality_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=True),
    sa.Column('timeframe_id', sa.UUID(), nullable=True),
    sa.Column('check_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rejection_reason', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['trading.symbols.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['trading.timeframes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_data_quality_checks_status', 'data_quality_checks', ['status'], unique=False, schema='trading')
    op.create_index('ix_data_quality_checks_symbol_tf_checked_at', 'data_quality_checks', ['symbol_id', 'timeframe_id', 'checked_at'], unique=False, schema='trading')
    op.create_table('market_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['trading.symbols.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_market_events_is_active', 'market_events', ['is_active'], unique=False, schema='trading')
    op.create_index('ix_market_events_symbol_event_type', 'market_events', ['symbol_id', 'event_type'], unique=False, schema='trading')
    op.create_table('market_regimes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('timeframe_id', sa.UUID(), nullable=False),
    sa.Column('regime', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['trading.symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['trading.timeframes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_market_regimes_regime', 'market_regimes', ['regime'], unique=False, schema='trading')
    op.create_index('ix_market_regimes_symbol_tf_detected_at', 'market_regimes', ['symbol_id', 'timeframe_id', 'detected_at'], unique=False, schema='trading')
    op.create_table('performance_by_strategy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading.trading_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['trading.strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_performance_by_strategy_strategy_period', 'performance_by_strategy', ['strategy_id', 'period_start', 'period_end'], unique=False, schema='trading')
    op.create_table('performance_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('gross_loss', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading.trading_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'trade_date', name='uq_performance_daily_account_trade_date'),
    schema='trading'
    )
    op.create_index('ix_performance_daily_trade_date', 'performance_daily', ['trade_date'], unique=False, schema='trading')
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('timeframe_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('signal_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('lot_size', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['trading.strategies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['symbol_id'], ['trading.symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['trading.timeframes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_signals_status', 'signals', ['status'], unique=False, schema='trading')
    op.create_index('ix_signals_symbol_tf_signal_time', 'signals', ['symbol_id', 'timeframe_id', 'signal_time'], unique=False, schema='trading')
    op.create_index('ix_signals_trace_id', 'signals', ['trace_id'], unique=False, schema='trading')
    op.create_table('strategy_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=True),
    sa.Column('timeframe_id', sa.UUID(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['trading.strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['trading.symbols.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['trading.timeframes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_strategy_configs_strategy_id', 'strategy_configs', ['strategy_id'], unique=False, schema='trading')
    op.create_index('ix_strategy_configs_symbol_tf', 'strategy_configs', ['symbol_id', 'timeframe_id'], unique=False, schema='trading')
    op.create_table('tick_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bid', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('ask', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('last', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('spread', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['trading.symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_tick_snapshots_symbol_event_time', 'tick_snapshots', ['symbol_id', 'event_time'], unique=False, schema='trading')
    op.create_table('execution_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('rejection_reason', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['trading.signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_execution_decisions_signal_id', 'execution_decisions', ['signal_id'], unique=False, schema='trading')
    op.create_index('ix_execution_decisions_trace_id', 'execution_decisions', ['trace_id'], unique=False, schema='trading')
    op.create_table('historical_edge_validations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('expectancy', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['trading.signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['trading.strategies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_historical_edge_validations_signal_id', 'historical_edge_validations', ['signal_id'], unique=False, schema='trading')
    op.create_index('ix_historical_edge_validations_strategy_id', 'historical_edge_validations', ['strategy_id'], unique=False, schema='trading')
    op.create_table('market_event_filters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_event_id', sa.UUID(), nullable=True),
    sa.Column('filter_name', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_event_id'], ['trading.market_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_market_event_filters_event_id_created_at', 'market_event_filters', ['market_event_id', 'created_at'], unique=False, schema='trading')
    op.create_table('pre_trade_simulations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('expected_profit', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('expected_drawdown', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('slippage_estimate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('simulated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['trading.signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_pre_trade_simulations_passed', 'pre_trade_simulations', ['passed'], unique=False, schema='trading')
    op.create_index('ix_pre_trade_simulations_signal_id', 'pre_trade_simulations', ['signal_id'], unique=False, schema='trading')
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('risk_per_trade_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('max_daily_loss_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('position_size_lot', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('stop_loss_pips', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('take_profit_pips', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('risk_reward_ratio', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['trading.signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_risk_assessments_passed', 'risk_assessments', ['passed'], unique=False, schema='trading')
    op.create_index('ix_risk_assessments_signal_id', 'risk_assessments', ['signal_id'], unique=False, schema='trading')
    op.create_table('signal_validations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('validator_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rejection_reason', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['trading.signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_signal_validations_signal_id', 'signal_validations', ['signal_id'], unique=False, schema='trading')
    op.create_index('ix_signal_validations_status', 'signal_validations', ['status'], unique=False, schema='trading')
    op.create_table('strategy_feedback_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['trading.signals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['trading.strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_strategy_feedback_events_strategy_id_created_at', 'strategy_feedback_events', ['strategy_id', 'created_at'], unique=False, schema='trading')
    op.create_table('strategy_selections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('timeframe_id', sa.UUID(), nullable=False),
    sa.Column('regime_id', sa.UUID(), nullable=True),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regime_id'], ['trading.market_regimes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['trading.strategies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['symbol_id'], ['trading.symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['trading.timeframes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_strategy_selections_symbol_tf_created_at', 'strategy_selections', ['symbol_id', 'timeframe_id', 'created_at'], unique=False, schema='trading')
    op.create_index('ix_strategy_selections_trace_id', 'strategy_selections', ['trace_id'], unique=False, schema='trading')
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_decision_id', sa.UUID(), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_decision_id'], ['trading.execution_decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_approval_requests_execution_decision_id', 'approval_requests', ['execution_decision_id'], unique=False, schema='trading')
    op.create_index('ix_approval_requests_status', 'approval_requests', ['status'], unique=False, schema='trading')
    op.create_table('execution_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('execution_decision_id', sa.UUID(), nullable=True),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('mt5_order_ticket', sa.BigInteger(), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=32), nullable=False),
    sa.Column('volume_lot', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('requested_price', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('deviation', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('broker_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_decision_id'], ['trading.execution_decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signal_id'], ['trading.signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['trading.symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mt5_order_ticket'),
    schema='trading'
    )
    op.create_index('ix_execution_orders_mt5_order_ticket', 'execution_orders', ['mt5_order_ticket'], unique=False, schema='trading')
    op.create_index('ix_execution_orders_signal_id', 'execution_orders', ['signal_id'], unique=False, schema='trading')
    op.create_index('ix_execution_orders_status', 'execution_orders', ['status'], unique=False, schema='trading')
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_order_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('mt5_position_ticket', sa.BigInteger(), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('volume_lot', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('profit', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading.trading_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execution_order_id'], ['trading.execution_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symbol_id'], ['trading.symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mt5_position_ticket'),
    schema='trading'
    )
    op.create_index('ix_positions_account_id_status', 'positions', ['account_id', 'status'], unique=False, schema='trading')
    op.create_index('ix_positions_mt5_position_ticket', 'positions', ['mt5_position_ticket'], unique=False, schema='trading')
    op.create_index('ix_positions_symbol_id_status', 'positions', ['symbol_id', 'status'], unique=False, schema='trading')
    op.create_table('position_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('unrealized_profit', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('swap', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('commission', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['trading.positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_position_snapshots_position_id_snapshot_time', 'position_snapshots', ['position_id', 'snapshot_time'], unique=False, schema='trading')
    op.create_table('trade_journals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('journal_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['trading.execution_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['position_id'], ['trading.positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signal_id'], ['trading.signals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_trade_journals_journal_type', 'trade_journals', ['journal_type'], unique=False, schema='trading')
    op.create_index('ix_trade_journals_trace_id_created_at', 'trade_journals', ['trace_id', 'created_at'], unique=False, schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_journals_trace_id_created_at', table_name='trade_journals', schema='trading')
    op.drop_index('ix_trade_journals_journal_type', table_name='trade_journals', schema='trading')
    op.drop_table('trade_journals', schema='trading')
    op.drop_index('ix_position_snapshots_position_id_snapshot_time', table_name='position_snapshots', schema='trading')
    op.drop_table('position_snapshots', schema='trading')
    op.drop_index('ix_positions_symbol_id_status', table_name='positions', schema='trading')
    op.drop_index('ix_positions_mt5_position_ticket', table_name='positions', schema='trading')
    op.drop_index('ix_positions_account_id_status', table_name='positions', schema='trading')
    op.drop_table('positions', schema='trading')
    op.drop_index('ix_execution_orders_status', table_name='execution_orders', schema='trading')
    op.drop_index('ix_execution_orders_signal_id', table_name='execution_orders', schema='trading')
    op.drop_index('ix_execution_orders_mt5_order_ticket', table_name='execution_orders', schema='trading')
    op.drop_table('execution_orders', schema='trading')
    op.drop_index('ix_approval_requests_status', table_name='approval_requests', schema='trading')
    op.drop_index('ix_approval_requests_execution_decision_id', table_name='approval_requests', schema='trading')
    op.drop_table('approval_requests', schema='trading')
    op.drop_index('ix_strategy_selections_trace_id', table_name='strategy_selections', schema='trading')
    op.drop_index('ix_strategy_selections_symbol_tf_created_at', table_name='strategy_selections', schema='trading')
    op.drop_table('strategy_selections', schema='trading')
    op.drop_index('ix_strategy_feedback_events_strategy_id_created_at', table_name='strategy_feedback_events', schema='trading')
    op.drop_table('strategy_feedback_events', schema='trading')
    op.drop_index('ix_signal_validations_status', table_name='signal_validations', schema='trading')
    op.drop_index('ix_signal_validations_signal_id', table_name='signal_validations', schema='trading')
    op.drop_table('signal_validations', schema='trading')
    op.drop_index('ix_risk_assessments_signal_id', table_name='risk_assessments', schema='trading')
    op.drop_index('ix_risk_assessments_passed', table_name='risk_assessments', schema='trading')
    op.drop_table('risk_assessments', schema='trading')
    op.drop_index('ix_pre_trade_simulations_signal_id', table_name='pre_trade_simulations', schema='trading')
    op.drop_index('ix_pre_trade_simulations_passed', table_name='pre_trade_simulations', schema='trading')
    op.drop_table('pre_trade_simulations', schema='trading')
    op.drop_index('ix_market_event_filters_event_id_created_at', table_name='market_event_filters', schema='trading')
    op.drop_table('market_event_filters', schema='trading')
    op.drop_index('ix_historical_edge_validations_strategy_id', table_name='historical_edge_validations', schema='trading')
    op.drop_index('ix_historical_edge_validations_signal_id', table_name='historical_edge_validations', schema='trading')
    op.drop_table('historical_edge_validations', schema='trading')
    op.drop_index('ix_execution_decisions_trace_id', table_name='execution_decisions', schema='trading')
    op.drop_index('ix_execution_decisions_signal_id', table_name='execution_decisions', schema='trading')
    op.drop_table('execution_decisions', schema='trading')
    op.drop_index('ix_tick_snapshots_symbol_event_time', table_name='tick_snapshots', schema='trading')
    op.drop_table('tick_snapshots', schema='trading')
    op.drop_index('ix_strategy_configs_symbol_tf', table_name='strategy_configs', schema='trading')
    op.drop_index('ix_strategy_configs_strategy_id', table_name='strategy_configs', schema='trading')
    op.drop_table('strategy_configs', schema='trading')
    op.drop_index('ix_signals_trace_id', table_name='signals', schema='trading')
    op.drop_index('ix_signals_symbol_tf_signal_time', table_name='signals', schema='trading')
    op.drop_index('ix_signals_status', table_name='signals', schema='trading')
    op.drop_table('signals', schema='trading')
    op.drop_index('ix_performance_daily_trade_date', table_name='performance_daily', schema='trading')
    op.drop_table('performance_daily', schema='trading')
    op.drop_index('ix_performance_by_strategy_strategy_period', table_name='performance_by_strategy', schema='trading')
    op.drop_table('performance_by_strategy', schema='trading')
    op.drop_index('ix_market_regimes_symbol_tf_detected_at', table_name='market_regimes', schema='trading')
    op.drop_index('ix_market_regimes_regime', table_name='market_regimes', schema='trading')
    op.drop_table('market_regimes', schema='trading')
    op.drop_index('ix_market_events_symbol_event_type', table_name='market_events', schema='trading')
    op.drop_index('ix_market_events_is_active', table_name='market_events', schema='trading')
    op.drop_table('market_events', schema='trading')
    op.drop_index('ix_data_quality_checks_symbol_tf_checked_at', table_name='data_quality_checks', schema='trading')
    op.drop_index('ix_data_quality_checks_status', table_name='data_quality_checks', schema='trading')
    op.drop_table('data_quality_checks', schema='trading')
    op.drop_index('ix_candles_symbol_tf_open_time', table_name='candles', schema='trading')
    op.drop_table('candles', schema='trading')
    op.drop_index('ix_broker_health_checks_is_healthy', table_name='broker_health_checks', schema='trading')
    op.drop_index('ix_broker_health_checks_checked_at', table_name='broker_health_checks', schema='trading')
    op.drop_table('broker_health_checks', schema='trading')
    op.drop_index('ix_account_snapshots_account_id_snapshot_time', table_name='account_snapshots', schema='trading')
    op.drop_table('account_snapshots', schema='trading')
    op.drop_index('ix_trading_accounts_broker_server', table_name='trading_accounts', schema='trading')
    op.drop_index('ix_trading_accounts_account_number', table_name='trading_accounts', schema='trading')
    op.drop_table('trading_accounts', schema='trading')
    op.drop_index('ix_timeframes_code', table_name='timeframes', schema='trading')
    op.drop_table('timeframes', schema='trading')
    op.drop_index('ix_symbols_name', table_name='symbols', schema='trading')
    op.drop_table('symbols', schema='trading')
    op.drop_index('ix_strategies_code', table_name='strategies', schema='trading')
    op.drop_table('strategies', schema='trading')
    op.drop_index('ix_safety_events_severity', table_name='safety_events', schema='trading')
    op.drop_index('ix_safety_events_event_type_created_at', table_name='safety_events', schema='trading')
    op.drop_table('safety_events', schema='trading')
    op.drop_index('ix_kill_switch_states_is_active_created_at', table_name='kill_switch_states', schema='trading')
    op.drop_table('kill_switch_states', schema='trading')
    # ### end Alembic commands ###
